### ISSUE TITLE
Use fragments of different types in query

### ISSUE THREAD

**Issue by jbreckel** [apollostack/apollo-client#763]
hey guys,
I am trying to use fragments for different types together like this:
```
const subjectInfo = createFragment(gql`
  fragment subjectInfo on Subject {
    id
    name
  }`
)
const businessAreaInfo = createFragment(gql`
  fragment businessAreaInfo on BusinessArea {
    id
    name
    subjects {
      ...subjectInfo
    }
  }`,
  [subjectInfo]
)
graphql(gql`
query {
  businessAreas {
    ...businessAreaInfo
  }
}
`, {
  fragments: businessAreaInfo
})
```

but the resulting query, that Apollo sends to the server, looks like this:
```
{
  businessAreas {
    ...businessAreaInfo
    ...subjectInfo
  }
}

fragment businessAreaInfo on BusinessArea {
  id
  name
  subjects {
  ...subjectInfo
  }
}

fragment subjectInfo on Subject {
  id
  name
}
```

**Comment by helfer** [comment]
Thanks for reporting @jbreckel I _think_ this should be solved after the refactor. I'll add it to the milestone just to make sure.

**Comment by jbreckel** [comment]
Thanks.

When do you think this will be published?

Do you have any recommendations how I can work around this issue?
Thanks in advance

**Comment by helfer** [comment]
@jbreckel we'll publish the next release this week, but because of the version bump it may take a few days for react-apollo to be updated as well.

In the meantime, a workaround would be to not use the subjectInfo fragment inside businessAreaInfo, and instead include the fields `id` and `name` directly.

**Comment by stubailo** [comment]
This is a result of some query manipulation we were doing before sending to the server, but we're removing that in 0.5 which should come out shortly. Follow along here: https://github.com/apollostack/apollo-client/issues/726

**Comment by stubailo** [comment]
Hmm, I tried to write a test to reproduce the issue but didn't succeed. Perhaps the issue is already fixed: https://github.com/apollostack/apollo-client/pull/790

**Comment by stubailo** [comment]
Let me know if you can make an app to reproduce it.

**Comment by jbreckel** [comment]
That is strange, when I use the most latest version of `apollo-client` and `react-apollo` the issue remains the same...
Can this be traced to a commit after the latest release?

**Comment by jbreckel** [comment]
Sorry guys, the problem sat in front of the PC.
I had done some huge mistakes with the query building.
