### ISSUE TITLE
resetStore seems to fire an extra query

### ISSUE THREAD

**Issue by booboothefool** [apollostack/apollo-client#820]
TestScreen (has `UserInfo` query on it) does this when I press logout: 

```
  logout() {
    const { client } = this.props;
    Actions.login();  // react-native-flux-router: go back to login
    AsyncStorage.multiRemove(['token1', 'token2']);
    client.resetStore();
  }
```

User is sent back to the login screen (does not have `UserInfo` query on it):
![screen shot 2016-10-21 at 3 22 33 am](https://cloud.githubusercontent.com/assets/13257645/19590087/08473f9a-973e-11e6-96ae-b06849d0f7fc.png)

^ After this happens, the store is reset: `APOLLO_STORE_RESET`

But `UserInfo` query, which was only on TestScreen, ends up running again when I'm not even there anymore (I'm back at the login screen).
![screen shot 2016-10-21 at 3 26 33 am](https://cloud.githubusercontent.com/assets/13257645/19590127/38077d30-973e-11e6-8704-0dc48412cd56.png)

Here is the result when I don't resetStore (no extra query, so this makes me think it's coming from resetStore): 
![screen shot 2016-10-21 at 3 34 19 am](https://cloud.githubusercontent.com/assets/13257645/19590335/598f4374-973f-11e6-9e18-c744b1b4320f.png)

**Comment by andrewnoh** [comment]
@helfer I can at least confirm my component is being unmounted. This happens right after `REACT_NATIVE_ROUTER_FLUX_RESET`, so there's no reason that query should still be active. 

Isn't that what `APOLLO_QUERY_STOP` does anyway? Kill the active query? 

Do you have any suggestions on how I can make sure that query is definitely dead, or have resetStore happen without rerunning active queries?

**Comment by helfer** [comment]
@andrewnoh is the QUERY_STOP action fired for the query that gets rerun after? If so, that's definitely not intended and might be a bug. Do you have a minimal reproduction or a failing test case that I could use to figure out what's going on?

**Comment by andrewnoh** [comment]
@helfer 

Yes, the queryId for APOLLO_QUERY_STOP and the APOLLO_QUERY_INIT that happens after APOLLO_STORE_RESET are the same. 

I made this for you: https://github.com/andrewnoh/apollo-client-issue-820-resetStore

You should see this result: 
![screen shot 2016-10-21 at 6 13 21 pm](https://cloud.githubusercontent.com/assets/13257645/19613426/7ad51c68-97ba-11e6-8ffe-b397957bb041.png)

Unfortunately Fortune Cookie API is down, but you should still get the idea. :P

**Comment by helfer** [comment]
@andrewnoh thanks for the repro! I've never run a react-native project before. Do I need to install a bunch of libraries/tools for this to work?

**Comment by andrewnoh** [comment]
You shouldn't need that much! Getting a React Native project is easier than getting a React project running imho lol. 

You just need: 
```
brew install node
brew install watchman
npm install -g react-native-cli
```

```install and update xcode```

server
```
npm install
npm start
```

client
```
npm install
react-native link
react-native run ios (or press the play button in xcode)
```

**Comment by helfer** [comment]
I think this would be much easier to debug for me if the repro wasn't in react native. For example, Redux devtools didn't work out of the box.

Anyway, I got it running, and I think I see the same problem that you have.

On the off chance that we somehow fixed this with our refactor (unlikely, but we should still try), can you update the example to use AC 0.5.0 and see if the error persists? If the only problem you're seeing is that there's an extra query fired (more of a nuisance than anything else), I won't try too hard to figure it out right now.

**Comment by helfer** [comment]
@andrewnoh are you still seeing this in 0.5.1?

**Comment by SamWyld** [comment]
We have the same problem with normal react (not native). Query init action is dispatched after resetStore is being called. In fact if I go back to the component this query belongs to and call resetStore again it would call the same query twice. It seems like something is not being unmounted.

**Comment by helfer** [comment]
@SamWyld oh, ok! If you could make a (relatively) minimal reproduction with just normal react, I think we could get this bug found and fixed pretty quickly! 🙂

**Comment by SamWyld** [comment]
I made a quick example for you:
https://github.com/SamWyld/resetStore-Issue

**Comment by alexeygolev** [comment]
Same situation with (not native) react and react-router. In fact we're just following the auth example from the docs. We do resetState and redirect to login. We even tried to resetState on login page (in case there is a race condition)

**Comment by calebmer** [comment]
Fixed with https://github.com/apollostack/apollo-client/commit/1626bdfff2c84d7a7652c308f10d0749796afc0d and released in `0.5.26` :tada:

**Comment by magbicaleman** [comment]
I'm still seeing this in `"react-apollo": "^1.0.0-rc.2"`, perhaps I'm doing something wrong. It seems that the query is still active.

**Comment by darkadept** [comment]
I'm still seeing this in 1.4.15. I'm following the instructions from here: http://dev.apollodata.com/react/auth.html.

It could be because my component has both a query and also does the reset. I'll have to check further into this.
